---
- hosts: test
  tasks: 
  - name: Get the ACL information in /etc/test.acl.txt remote file
    acl: name=/etc/test.acl.txt entity=test etype=user permissions="rw" state=present
    register: aclinfo
  - debug: msg={{ aclinfo }}     

