---
- hosts: apacheweb
  user: root
  connection: ssh
  gather_facts: no
  vars:
    - playbook_version: 0.0b
  vars_files:
      - conf/copyright.yml
      - conf/webdefaults.yml
  vars_prompt:
   - name: pkgtoinstall
     prompt: Install which Package?
     default: telnet
     private: no
  tasks:
     - name: Installing the prompted package
       yum: name={{ pkgtoinstall }} state=latest

