---
- hosts: test
  connection: ssh
  gather_facts: no
  sudo: yes
  tasks:
  - name: Installing Apache Web
    action: yum name=httpd state=latest
  - name: Ensure Apache is runninfg
    service: name=httpd state=restarted enabled=yes
  
