---
- hosts: apacheweb
  sudo: yes
  vars:
   playbook_version: 1.0.b
  tasks:
   - name: Local Variable Display
     set_fact: 
         singlefact: SOMETHING
   - debug: msg={{ playbook_version }} 
   - debug: msg={{ singlefact }}
