---
- hosts: apacheweb
  gather_facts: yes
  tasks:
  - name: Does a file or directory or link exist
    stat: path=/home/test/abc
    register: p
  - debug: msg="The path exist and it is a directory"
    when: p.stat.isdir is defined and p.stat.isdir
