---
- hosts: apacheweb
  user: root
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install telnet and lynx packages
    yum: name={{ item }} state=latest
    with_items:
     - telnet
     - lynx
    tags:
    - install
  - name: Verify Installation
    command: yum list installed | grep telnet > /etc/ansible/playbook/logs/logs.log
    tags:
    - verify
 
