---
- hosts: local
  sudo: yes
  gather_facts: no
  tasks:
  - name: Install Apache Tomcat
    action: yum name=tomcat state=latest

  - name: Waiting for port 8080 to listen
    wait_for:
     port: 8080
     state: started
  - name: Veryfying Lynx
    action: yum name=lynx state=present
