---
- hosts: apacheweb
  sudo: yes
  gather_facts: yes
  connection: ssh
  tasks:
   - name: Install Apache for Redhat
     yum: pkg=httpd state=latest
     when: ansible_os_family == 'RedHat'
   - name: Installing Apache for Debian
     apt: name=apache2 state=present
     when: ansible_os_family == 'Debian'
