---
- hosts: apacheweb
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installing httpd
    ignore_errors: yes
    yum: naame=httpd state=present
   
  
  - name: Display home
    shell: ls -la /home
    register: result
  - debug: var=result
 
