---
- hosts: apacheweb
  sudo: yes
  gather_facts: no
  tasks:
    - include: play/play.yml
    - name: Verifying Telnet is installed 
      shell: yum list installed | grep telnet > /home/test/pkg.log
 
