---
- hosts: apacheweb
  sudo: yes
  gather_facts: no
  vars:
   - user: PRAKASH 
   - passs: PASSWORD
   - conn: SSH
  tasks:
  - name: Installing templates in remote server
    template: src=test.conf.j2 dest=/home/test/test.conf.j2 owner=root group=root mode=750


