--- # My First Playbook for ansible
- hosts: apacheweb
  connection: ssh
  user: root
  sudo: yes
  
  gather_facts: no
  vars:
   playbook_version: 0.1.b
  vars_files:
   - conf/copyright.yml
   - conf/webdefaults.yml
  
  tasks:
    - name: Install telnet
      yum: pkg=telnet state=latest 
