---
- hosts: apacheweb
  become: true
  user: root
  connection: ssh
  tasks:
  - name: Install httpd
    yum: name=httpd state=latest
   # tags:
    # - httpd

  - name: Install telnet
    yum: name=telnet state=latest
   # tags:
    # - telnet

  - name: Install lynx
    yum: name=lynx state=latest
   # tags:
    # - lynx 
