---
- hosts: apacheweb
  sudo: yes
  gather_facts: no
  
  tasks:
   - name: Install telnet
     yum: pkg=telnet state=present update_cache=yes
     tags:
       - installtelnet
   
   - name: Remove telnet
     yum: pkg=telnet state=absent
     tags:
       - removetelnet
